---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi
  tasks:
    
    - name: start server HTTP
      ibmi_tcp_server_service:
        name_list: ['*HTTP']
        state: 'started'
        extra_parameters: 'INSTANCE(IWADFT)'
        joblog: true
      register: start_result
    - debug:
       var: start_result
